// <auto-generated />
using System;
using NguyetnhanPhohien.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NguyetnhanPhohien.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NguyetnhanPhohien.Domain.Entities.AutoReplyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacebookPageId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReplyText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacebookPageId");

                    b.ToTable("AutoReplyRules");
                });

            modelBuilder.Entity("NguyetnhanPhohien.Domain.Entities.BotSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiPrompt")
                        .HasColumnType("text");

                    b.Property<string>("DefaultReply")
                        .HasColumnType("text");

                    b.Property<Guid>("FacebookPageId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAiEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FacebookPageId");

                    b.ToTable("BotSettings");
                });

            modelBuilder.Entity("NguyetnhanPhohien.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacebookPageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FacebookPageId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("NguyetnhanPhohien.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FacebookSenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacebookSenderId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("NguyetnhanPhohien.Domain.Entities.FacebookPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PageId")
                        .IsUnique();

                    b.ToTable("FacebookPages");
                });

            modelBuilder.Entity("NguyetnhanPhohien.Domain.Entities.FacebookPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FacebookPageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FacebookPageId");

                    b.ToTable("FacebookPosts");
                });

            modelBuilder.Entity("NguyetnhanPhohien.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<int>("SenderType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("NguyetnhanPhohien.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NguyetnhanPhohien.Domain.Entities.AutoReplyRule", b =>
                {
                    b.HasOne("NguyetnhanPhohien.Domain.Entities.FacebookPage", "Page")
                        .WithMany()
                        .HasForeignKey("FacebookPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("NguyetnhanPhohien.Domain.Entities.BotSetting", b =>
                {
                    b.HasOne("NguyetnhanPhohien.Domain.Entities.FacebookPage", "Page")
                        .WithMany()
                        .HasForeignKey("FacebookPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("NguyetnhanPhohien.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("NguyetnhanPhohien.Domain.Entities.Customer", "Customer")
                        .WithMany("Conversations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NguyetnhanPhohien.Domain.Entities.FacebookPage", "Page")
                        .WithMany("Conversations")
                        .HasForeignKey("FacebookPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("NguyetnhanPhohien.Domain.Entities.FacebookPost", b =>
                {
                    b.HasOne("NguyetnhanPhohien.Domain.Entities.FacebookPage", "Page")
                        .WithMany("Posts")
                        .HasForeignKey("FacebookPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("NguyetnhanPhohien.Domain.Entities.Message", b =>
                {
                    b.HasOne("NguyetnhanPhohien.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("NguyetnhanPhohien.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("NguyetnhanPhohien.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Conversations");
                });

            modelBuilder.Entity("NguyetnhanPhohien.Domain.Entities.FacebookPage", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
